"*":
  - type: element
    element:
      scope:
        selector: a
      label:
        template: "{innerText}"
      trigger:
        type: open
  - type: element
    element:
      scope:
        selector: button
      label:
        template: button
      trigger:
        type: click
  - type: element
    element:
      scope:
        selector: input
      label:
        template: input
      trigger:
        type: focus
  - type: element
    element:
      scope:
        selector: "[type=checkbox]"
      label:
        template: input
      trigger:
        type: click
  - type: element
    element:
      scope:
        selector: "[type=radio]"
      label:
        template: input
      trigger:
        type: click
  - type: element
    element:
      scope:
        selector: "[type=file]"
      label:
        template: input
      trigger:
        type: click
  - type: element
    element:
      scope:
        selector: select
      label:
        template: input
      trigger:
        type: focus
  - type: element
    element:
      scope:
        selector: textarea
      label:
        template: input
      trigger:
        type: focus
  - type: element
    element:
      scope:
        selector: "[role=link]"
      label:
        template: "{innerText}"
      trigger:
        type: open
  - type: element
    element:
      scope:
        selector: "[role=button]"
      label:
        template: button
      trigger:
        type: click
  - type: element
    element:
      scope:
        selector: "[role=checkbox]"
      label:
        template: button
      trigger:
        type: click
